language: go
sudo: false
branched:
  only:
    - master
    - develop
    - feature/*
go:
  - 1.4.3
  - 1.5.4
  - 1.6.4
  - 1.7.5
  - 1.8
  - tip
install:
  - make setup
script:
  - test -z "$(golint ./... | tee /dev/stderr)"
  - go vet .
  - make test
  - make benchmark
matrix:
  allow_failures:
    - go: tip
