language: go
sudo: false
branches:
  only:
    - master
    - develop
    - feature/*
go:
  - 1.7.6
  - 1.8.7
  - 1.9.6
  - 1.10.2
  - tip
install:
  - go get -u golang.org/x/lint/golint
script:
  - test -z "$(golint ./... | tee /dev/stderr)"
  - go vet .
  - go test -v .
  - go test -bench . -benchmem
matrix:
  allow_failures:
    - go: tip
